const jqPlaylistPath = "./audio/jqPlaylist/";
const jqPlaylist = [
	{
		path: `${jqPlaylistPath}Count Bass D, MF DOOM - Quite Buttery.mp3`,
		name: "Quite Buttery",
		artists: ["Count Bass D", "MF DOOM"],
		artist: "Count Bass D",
		genres: ["alternative hip hop", "jazz rap"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Dwight Spitz",
		album_artist: "Count Bass D",
		duration: 66039,
		year: "2002",
		date: "2002",
		track_number: 16,
		tracks_count: 25,
		song_id: "6um8falqCT0st7YLJlgaWs",
		explicit: true,
		publisher: "CountBassD.com",
		url: "https://open.spotify.com/track/6um8falqCT0st7YLJlgaWs",
		isrc: "US25T0610958",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273b341b024365c7629e6b94c0c",
		copyright_text: "(C) 2002 CountBassD.com",
		download_url: null,
		lyrics: null,
		popularity: 59,
		album_id: "5pYyzn5NVbi1na3l6Pw75O",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 3,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Bob James - Angela (Theme From Taxi).mp3`,
		name: "Angela (Theme From Taxi)",
		artists: ["Bob James"],
		artist: "Bob James",
		genres: ["jazz funk", "jazz piano", "smooth jazz"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Touchdown",
		album_artist: "Bob James",
		duration: 345160,
		year: "1977",
		date: "1977-07-20",
		track_number: 1,
		tracks_count: 5,
		song_id: "4iKU4J0AjDeDXOCgpuol0C",
		explicit: false,
		publisher: "evosound",
		url: "https://open.spotify.com/track/4iKU4J0AjDeDXOCgpuol0C",
		isrc: "USKO10501565",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27367d22420aae725b1107ceffa",
		copyright_text: "1978 Tappan Zee Records under license to Evolution Ltd.",
		download_url: null,
		lyrics: null,
		popularity: 48,
		album_id: "5ooWmAVLqcWvDDOid6hCC6",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 2,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Charles Stepney - Around The House.mp3`,
		name: "Around The House",
		artists: ["Charles Stepney"],
		artist: "Charles Stepney",
		genres: [],
		disc_number: 1,
		disc_count: 1,
		album_name: "Step on Step",
		album_artist: "Charles Stepney",
		duration: 254120,
		year: "2022",
		date: "2022-09-09",
		track_number: 13,
		tracks_count: 23,
		song_id: "3rwE2mQboEl6zbYnKGZVJP",
		explicit: false,
		publisher: "International Anthem",
		url: "https://open.spotify.com/track/3rwE2mQboEl6zbYnKGZVJP",
		isrc: "QM84B2255013",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273f68d824b265a19c99e71c888",
		copyright_text: "2022 International Anthem",
		download_url: null,
		lyrics: null,
		popularity: 0,
		album_id: "2bTfoaj3ik86wBelmfL4Gh",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 1,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Lil Yachty - drive ME crazy!.mp3`,
		name: "drive ME crazy!",
		artists: ["Lil Yachty"],
		artist: "Lil Yachty",
		genres: ["atl hip hop", "melodic rap", "rap", "trap"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Let’s Start Here.",
		album_artist: "Lil Yachty",
		duration: 229804,
		year: "2023",
		date: "2023-01-27",
		track_number: 8,
		tracks_count: 14,
		song_id: "6luBKkFUt5wTwz7hpLhp12",
		explicit: true,
		publisher: "Quality Control Music/Motown Records",
		url: "https://open.spotify.com/track/6luBKkFUt5wTwz7hpLhp12",
		isrc: "USUG12207176",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2736f578b21bce56056473da7e6",
		copyright_text:
			"© 2023 Quality Control Music, LLC, under exclusive license to UMG Recordings, Inc.",
		download_url: null,
		lyrics: null,
		popularity: 75,
		album_id: "6Per97deaWqrJlKQNX8RGK",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 4,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Faye Webster - Better Distractions.mp3`,
		name: "Better Distractions",
		artists: ["Faye Webster"],
		artist: "Faye Webster",
		genres: ["atlanta indie", "indie pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "I Know I'm Funny haha",
		album_artist: "Faye Webster",
		duration: 249985,
		year: "2021",
		date: "2021-06-25",
		track_number: 1,
		tracks_count: 11,
		song_id: "3CmcswzHOACDjooV1KLULN",
		explicit: false,
		publisher: "Secretly Canadian",
		url: "https://open.spotify.com/track/3CmcswzHOACDjooV1KLULN",
		isrc: "US38W2042601",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273c699d66824a938624c44c2b7",
		copyright_text: "2021 Secretly Canadian",
		download_url: null,
		lyrics: null,
		popularity: 58,
		album_id: "424bxvpYyNDM2DFFibeKs0",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 5,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Viktor Vaughn, MF DOOM - Can I Watch (feat. Apani B as Nikki).mp3`,
		name: "Can I Watch? (feat. Apani B as Nikki)",
		artists: ["Viktor Vaughn", "MF DOOM", "Apani B"],
		artist: "Viktor Vaughn",
		genres: ["abstract hip hop", "alternative hip hop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Vaudeville Villain",
		album_artist: "Viktor Vaughn",
		duration: 267440,
		year: "2003",
		date: "2003",
		track_number: 9,
		tracks_count: 17,
		song_id: "4i4P1ACAeWcyJTxQSd0prx",
		explicit: false,
		publisher: "Sound Ink",
		url: "https://open.spotify.com/track/4i4P1ACAeWcyJTxQSd0prx",
		isrc: "QMFMG1316698",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273d97a55d6ace2bf9e8ccb8cb1",
		copyright_text: "(C) 2003 Sound Ink Records",
		download_url: null,
		lyrics: null,
		popularity: 56,
		album_id: "7HPjcPD2cr8E5oHvVAmBp7",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 6,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}King Geedorah - Next Levels.mp3`,
		name: "Next Levels",
		artists: ["King Geedorah"],
		artist: "King Geedorah",
		genres: ["alternative hip hop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Take Me To Your Leader",
		album_artist: "King Geedorah",
		duration: 229320,
		year: "2003",
		date: "2003-06-17",
		track_number: 6,
		tracks_count: 13,
		song_id: "58MeeOMk6PMQxXWY9YCNPD",
		explicit: false,
		publisher: "Big Dada",
		url: "https://open.spotify.com/track/58MeeOMk6PMQxXWY9YCNPD",
		isrc: "GBCFB0300215",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273de20cdc5935096897bb687fc",
		copyright_text: "2003 Big Dada",
		download_url: null,
		lyrics: null,
		popularity: 66,
		album_id: "1mrhahrlJu5JfzgeV6Cy8t",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 7,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Madvillain, Madlib, MF DOOM - Curls.mp3`,
		name: "Curls",
		artists: ["Madvillain", "Madlib", "MF DOOM"],
		artist: "Madvillain",
		genres: [
			"abstract hip hop",
			"alternative hip hop",
			"hip hop",
			"psychedelic hip hop",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Madvillainy",
		album_artist: "Madvillain",
		duration: 95506,
		year: "2004",
		date: "2004-03-24",
		track_number: 9,
		tracks_count: 22,
		song_id: "0V3nTTKA24XKCayp8igU4l",
		explicit: true,
		publisher: "Stones Throw Records",
		url: "https://open.spotify.com/track/0V3nTTKA24XKCayp8igU4l",
		isrc: "US2S70465009",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27374dc897ea75402db37ef239a",
		copyright_text: "2004 Stones Throw Records",
		download_url: null,
		lyrics: null,
		popularity: 64,
		album_id: "19bQiwEKhXUBJWY6oV3KZk",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 8,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}KIRBY - Pineapple Cognac.mp3`,
		name: "Pineapple Cognac",
		artists: ["KIRBY"],
		artist: "KIRBY",
		genres: ["alternative r&b", "indie triste"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Pineapple Cognac",
		album_artist: "KIRBY",
		duration: 134166,
		year: "2022",
		date: "2022-07-22",
		track_number: 1,
		tracks_count: 1,
		song_id: "6WWBltBaOkJ7qpcNVO4jeV",
		explicit: true,
		publisher: "KIRBY",
		url: "https://open.spotify.com/track/6WWBltBaOkJ7qpcNVO4jeV",
		isrc: "TCAGH2294445",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273009f54dbf00b23b59c5ca2d8",
		copyright_text: "2022 KIRBY",
		download_url: null,
		lyrics: null,
		popularity: 29,
		album_id: "29R9YV27YP2ZZI7P8x58mM",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 10,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Aretha Franklin - Day Dreaming.mp3`,
		name: "Day Dreaming",
		artists: ["Aretha Franklin"],
		artist: "Aretha Franklin",
		genres: [
			"classic soul",
			"jazz blues",
			"memphis soul",
			"neo soul",
			"soul",
			"southern soul",
			"vocal jazz",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Young, Gifted and Black",
		album_artist: "Aretha Franklin",
		duration: 239960,
		year: "1972",
		date: "1972-01-24",
		track_number: 2,
		tracks_count: 12,
		song_id: "7L4G39PVgMfaeHRyi1ML7y",
		explicit: false,
		publisher: "Rhino Atlantic",
		url: "https://open.spotify.com/track/7L4G39PVgMfaeHRyi1ML7y",
		isrc: "USAT20801194",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273ee5fcff519d1098aa5de990d",
		copyright_text:
			"© 1972 Atlantic Recording Corp., manufactured and marketed by Rhino Entertainment Company, a Warner Music Group Company",
		download_url: null,
		lyrics: null,
		popularity: 62,
		album_id: "0k5C3Z7w7uQpyGFQEzl7yB",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 9,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}binki - Sea Sick.mp3`,
		name: "Sea Sick",
		artists: ["binki"],
		artist: "binki",
		genres: ["modern indie pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Sea Sick",
		album_artist: "binki",
		duration: 130714,
		year: "2019",
		date: "2019-09-05",
		track_number: 1,
		tracks_count: 1,
		song_id: "3qiX7QXv6w6y4wsr5KP6U1",
		explicit: false,
		publisher: "binki",
		url: "https://open.spotify.com/track/3qiX7QXv6w6y4wsr5KP6U1",
		isrc: "QZ93L1954287",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2730f7d021f886c8f5444e84d50",
		copyright_text: "2019 binki",
		download_url: null,
		lyrics: null,
		popularity: 58,
		album_id: "1XQYd61d9bQA3ba5xUrhKB",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 11,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Tommy Richman - ELECTRIFY TONIGHT.mp3`,
		name: "ELECTRIFY TONIGHT",
		artists: ["Tommy Richman"],
		artist: "Tommy Richman",
		genres: ["chill abstract hip hop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "ALLIGATOR",
		album_artist: "Tommy Richman",
		duration: 154730,
		year: "2022",
		date: "2022-10-28",
		track_number: 2,
		tracks_count: 7,
		song_id: "0nifVdzF4R6WT2qITFJKeu",
		explicit: true,
		publisher: "Boom.Records",
		url: "https://open.spotify.com/track/0nifVdzF4R6WT2qITFJKeu",
		isrc: "QM24S2205357",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2735b2a25ea51b6b7c92dd85622",
		copyright_text: "2022 Boom.Records",
		download_url: null,
		lyrics: null,
		popularity: 48,
		album_id: "2fS7BLnNrjXc9s7WmGmyoH",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 13,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}MAX - GUCCI BAG.mp3`,
		name: "GUCCI BAG",
		artists: ["MAX"],
		artist: "MAX",
		genres: ["singer-songwriter pop", "teen pop", "viral pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "GUCCI BAG",
		album_artist: "MAX",
		duration: 134193,
		year: "2022",
		date: "2022-04-29",
		track_number: 1,
		tracks_count: 1,
		song_id: "08G63QA6FMXwaABEN6syRb",
		explicit: false,
		publisher: "Warner Records",
		url: "https://open.spotify.com/track/08G63QA6FMXwaABEN6syRb",
		isrc: "USWB12201013",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2736e930f4ddbdaae6d33784e03",
		copyright_text:
			"© 2022 Colour Vision Records, under exclusive license to Warner Records Inc.",
		download_url: null,
		lyrics: null,
		popularity: 46,
		album_id: "2uglKnENyDI1cz6PxM37dY",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 12,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Adi Oasis - Adonis - feat. KIRBY.mp3`,
		name: "Adonis - feat. KIRBY",
		artists: ["Adi Oasis", "KIRBY"],
		artist: "Adi Oasis",
		genres: ["indie r&b", "indie soul"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Adonis",
		album_artist: "Adi Oasis",
		duration: 219146,
		year: "2022",
		date: "2022-11-16",
		track_number: 1,
		tracks_count: 3,
		song_id: "1Ol7rmDYnjXadnWaEvY9em",
		explicit: true,
		publisher: "Unity Records",
		url: "https://open.spotify.com/track/1Ol7rmDYnjXadnWaEvY9em",
		isrc: "FRD9M2201110",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2733d5e9fefa8100de03dafbde6",
		copyright_text: "2022 Adi Oasis under exclusive license to Unity Records",
		download_url: null,
		lyrics: null,
		popularity: 41,
		album_id: "0rE9cJ5I2j2SpbKegSCTFW",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 14,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Tyler, The Creator - DOGTOOTH.mp3`,
		name: "DOGTOOTH",
		artists: ["Tyler, The Creator"],
		artist: "Tyler, The Creator",
		genres: ["hip hop", "rap"],
		disc_number: 1,
		disc_count: 1,
		album_name: "DOGTOOTH",
		album_artist: "Tyler, The Creator",
		duration: 161041,
		year: "2023",
		date: "2023-03-27",
		track_number: 1,
		tracks_count: 1,
		song_id: "0judK8TqYfvwUohBngUxrE",
		explicit: true,
		publisher: "Columbia",
		url: "https://open.spotify.com/track/0judK8TqYfvwUohBngUxrE",
		isrc: "USQX92301932",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2732ee031f2335d35b2e6c7bc40",
		copyright_text:
			"(P) 2023 Columbia Records, a Division of Sony Music Entertainment, as exclusive licensee",
		download_url: null,
		lyrics: null,
		popularity: 29,
		album_id: "1pdqT6DBwIA0WElEspOA0v",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 15,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Sudan Archives - Selfish Soul.mp3`,
		name: "Selfish Soul",
		artists: ["Sudan Archives"],
		artist: "Sudan Archives",
		genres: [
			"afrofuturism",
			"alternative r&b",
			"experimental r&b",
			"indie soul",
			"la pop",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Natural Brown Prom Queen",
		album_artist: "Sudan Archives",
		duration: 142666,
		year: "2022",
		date: "2022-09-09",
		track_number: 5,
		tracks_count: 18,
		song_id: "3XqP0HAPdDN3Lkdoufds20",
		explicit: false,
		publisher: "Stones Throw Records",
		url: "https://open.spotify.com/track/3XqP0HAPdDN3Lkdoufds20",
		isrc: "US2S72249005",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2739c351edcaee4de7d242e7aea",
		copyright_text: "2022 Stones Throw Records",
		download_url: null,
		lyrics: null,
		popularity: 55,
		album_id: "1QSo9HgowUqAc5BI3AdkqN",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 17,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}JPEGMAFIA, Danny Brown - Lean Beef Patty.mp3`,
		name: "Lean Beef Patty",
		artists: ["JPEGMAFIA", "Danny Brown"],
		artist: "JPEGMAFIA",
		genres: [
			"alternative hip hop",
			"experimental hip hop",
			"industrial hip hop",
			"underground hip hop",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Lean Beef Patty",
		album_artist: "JPEGMAFIA",
		duration: 107567,
		year: "2023",
		date: "2023-03-13",
		track_number: 1,
		tracks_count: 1,
		song_id: "1qbADMsKCFmu08MhWPTZpb",
		explicit: true,
		publisher:
			"2023 PEGGY under exclusive license to AWAL Recordings America, Inc.",
		url: "https://open.spotify.com/track/1qbADMsKCFmu08MhWPTZpb",
		isrc: "QM4TX2330850",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273bed396ed8c51de6bd63495b0",
		copyright_text:
			"(C) 2023 PEGGY under exclusive license to AWAL Recordings America, Inc.",
		download_url: null,
		lyrics: null,
		popularity: 44,
		album_id: "5ee7NlaQZi5TYOXRghp04b",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 18,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Gold Celeste - Grand New Spin.mp3`,
		name: "Grand New Spin",
		artists: ["Gold Celeste"],
		artist: "Gold Celeste",
		genres: ["indie garage rock", "neo-psychedelic", "norwegian psychedelic"],
		disc_number: 1,
		disc_count: 1,
		album_name: "The Glow",
		album_artist: "Gold Celeste",
		duration: 215333,
		year: "2015",
		date: "2015-09-11",
		track_number: 5,
		tracks_count: 11,
		song_id: "2RD1r9eKDTRs6hiN9RR9UC",
		explicit: false,
		publisher: "Riot Factory",
		url: "https://open.spotify.com/track/2RD1r9eKDTRs6hiN9RR9UC",
		isrc: "NODAX1509105",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273d70ce1e9be8e75f9733c0b63",
		copyright_text: "Riot Factory 2015",
		download_url: null,
		lyrics: null,
		popularity: 41,
		album_id: "3Y7KqU1su7HNrU8nujEYWk",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 19,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Ahmad Jamal Trio - I Love Music.mp3`,
		name: "I Love Music",
		artists: ["Ahmad Jamal Trio"],
		artist: "Ahmad Jamal Trio",
		genres: ["bebop", "jazz", "jazz trio", "soul jazz"],
		disc_number: 1,
		disc_count: 1,
		album_name: "The Awakening",
		album_artist: "Ahmad Jamal Trio",
		duration: 442440,
		year: "1970",
		date: "1970",
		track_number: 2,
		tracks_count: 7,
		song_id: "4MIPpjKWw1lLVwS6tLhis1",
		explicit: false,
		publisher: "Impulse!",
		url: "https://open.spotify.com/track/4MIPpjKWw1lLVwS6tLhis1",
		isrc: "USMC17052097",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2732eceabbc54b316b88e0bd8e7",
		copyright_text: "© 1997 GRP Records Inc.",
		download_url: null,
		lyrics: null,
		popularity: 49,
		album_id: "5oSVYKZLKGCmwYqmJ7AZnO",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 16,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}So!YoON! - Smoke Sprite (feat. RM of BTS).mp3`,
		name: "Smoke Sprite (feat. RM of BTS)",
		artists: ["So!YoON!", "RM"],
		artist: "So!YoON!",
		genres: ["korean indie rock"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Episode1 : Love",
		album_artist: "So!YoON!",
		duration: 242200,
		year: "2023",
		date: "2023-03-14",
		track_number: 2,
		tracks_count: 11,
		song_id: "5YSkDxmHvzSDWTu4MaEtfa",
		explicit: false,
		publisher: "MAGIC STRAWBERRY SOUND",
		url: "https://open.spotify.com/track/5YSkDxmHvzSDWTu4MaEtfa",
		isrc: "KRF252300305",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2733f8adef16f0ae1c05f7c51be",
		copyright_text:
			"2023 MAGIC STRAWBERRY SOUND,under license to Kakao Entertainment",
		download_url: null,
		lyrics: null,
		popularity: 71,
		album_id: "7yoMXU6kgxjIsowenBxzwD",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 21,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Jesse Barrera - No Reservations.mp3`,
		name: "No Reservations",
		artists: ["Jesse Barrera"],
		artist: "Jesse Barrera",
		genres: ["bedroom r&b", "chill r&b"],
		disc_number: 1,
		disc_count: 1,
		album_name: "No Reservations",
		album_artist: "Jesse Barrera",
		duration: 183357,
		year: "2023",
		date: "2023-02-03",
		track_number: 1,
		tracks_count: 1,
		song_id: "60DFlM3IXtn4y1yvbbGbfO",
		explicit: false,
		publisher: "THE JB CAVE Records",
		url: "https://open.spotify.com/track/60DFlM3IXtn4y1yvbbGbfO",
		isrc: "QZFYZ2391348",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273f63b0cd0f60dea54693a1eb0",
		copyright_text: "2023 THE JB CAVE Records",
		download_url: null,
		lyrics: null,
		popularity: 56,
		album_id: "0eG3xAfpbnkfytXoElMF8b",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 23,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Benny Sings - Pyjamas (feat. Remi Wolf).mp3`,
		name: "Pyjamas (feat. Remi Wolf)",
		artists: ["Benny Sings", "Remi Wolf"],
		artist: "Benny Sings",
		genres: ["dutch pop", "indie soul"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Pyjamas (feat. Remi Wolf)",
		album_artist: "Benny Sings",
		duration: 168240,
		year: "2023",
		date: "2023-03-09",
		track_number: 1,
		tracks_count: 4,
		song_id: "0LuB69EEijTVyNHOXHiqhN",
		explicit: false,
		publisher: "Stones Throw Records",
		url: "https://open.spotify.com/track/0LuB69EEijTVyNHOXHiqhN",
		isrc: "NLX5C2200011",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273e2720633bcf81d01c3c9a58d",
		copyright_text: "2023 Stones Throw Records",
		download_url: null,
		lyrics: null,
		popularity: 49,
		album_id: "0AmJGPvtL6Kj0MBp7gh8BK",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 20,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}FIG - Splinter.mp3`,
		name: "Splinter",
		artists: ["FIG"],
		artist: "FIG",
		genres: ["modern indie pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Splinter",
		album_artist: "FIG",
		duration: 167131,
		year: "2022",
		date: "2022-08-25",
		track_number: 1,
		tracks_count: 2,
		song_id: "4iKfmaKGc59LZXQNK7nAgf",
		explicit: false,
		publisher: "Cob Stand LLC",
		url: "https://open.spotify.com/track/4iKfmaKGc59LZXQNK7nAgf",
		isrc: "QM24S2203717",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2731ef990684b73f82c9efc859b",
		copyright_text: "2022 Cob Stand LLC",
		download_url: null,
		lyrics: null,
		popularity: 34,
		album_id: "5xQJYeIxVY2xJngtdtGz11",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 22,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}keshi - LIMBO.mp3`,
		name: "LIMBO",
		artists: ["keshi"],
		artist: "keshi",
		genres: ["chill r&b"],
		disc_number: 1,
		disc_count: 1,
		album_name: "GABRIEL",
		album_artist: "keshi",
		duration: 212784,
		year: "2022",
		date: "2022-03-25",
		track_number: 10,
		tracks_count: 12,
		song_id: "2bdVgAQgosGUJoViVDNeOV",
		explicit: true,
		publisher: "Island Records",
		url: "https://open.spotify.com/track/2bdVgAQgosGUJoViVDNeOV",
		isrc: "USUM72123297",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27319aff2da63b211d75341e8eb",
		copyright_text: "© 2022 Island Records, a division of UMG Recordings, Inc.",
		download_url: null,
		lyrics: null,
		popularity: 80,
		album_id: "1WVIJaAboRSwJOe4u0n0Q7",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 24,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}MICHELLE - THE PEACH.mp3`,
		name: "THE PEACH",
		artists: ["MICHELLE"],
		artist: "MICHELLE",
		genres: ["bedroom pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "THE PEACH",
		album_artist: "MICHELLE",
		duration: 146917,
		year: "2023",
		date: "2023-03-15",
		track_number: 1,
		tracks_count: 1,
		song_id: "6KCL9FON6UWWymafgIwECG",
		explicit: true,
		publisher: "NME",
		url: "https://open.spotify.com/track/6KCL9FON6UWWymafgIwECG",
		isrc: "QZVEM2307757",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27351609d6f4bb1486323740e9e",
		copyright_text:
			"2023 Atlantic Recording Corporation, under license to NME Networks Media Limited for the world",
		download_url: null,
		lyrics: null,
		popularity: 47,
		album_id: "6KUysdIaL4wtPiRXFAIYUI",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 25,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Kali Uchis - Love Between....mp3`,
		name: "Love Between...",
		artists: ["Kali Uchis"],
		artist: "Kali Uchis",
		genres: ["colombian pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Red Moon In Venus",
		album_artist: "Kali Uchis",
		duration: 155083,
		year: "2023",
		date: "2023-03-03",
		track_number: 4,
		tracks_count: 15,
		song_id: "128I36bDgYHU9l2QcgEGcd",
		explicit: false,
		publisher: "Geffen Records",
		url: "https://open.spotify.com/track/128I36bDgYHU9l2QcgEGcd",
		isrc: "USUM72219477",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27381fccd758776d16b87721b17",
		copyright_text: "© 2023 Geffen Records",
		download_url: null,
		lyrics: null,
		popularity: 64,
		album_id: "5OZ44LaqZbpP3m9B3oT8br",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 26,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}The Beatles - Do You Want To Know A Secret - Remastered 2009.mp3`,
		name: "Do You Want To Know A Secret - Remastered 2009",
		artists: ["The Beatles"],
		artist: "The Beatles",
		genres: [
			"british invasion",
			"classic rock",
			"merseybeat",
			"psychedelic rock",
			"rock",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Please Please Me (Remastered)",
		album_artist: "The Beatles",
		duration: 117013,
		year: "1963",
		date: "1963-03-22",
		track_number: 11,
		tracks_count: 14,
		song_id: "7Aobt67JnaF7qN8jCCKvHq",
		explicit: false,
		publisher: "EMI Catalogue",
		url: "https://open.spotify.com/track/7Aobt67JnaF7qN8jCCKvHq",
		isrc: "GBAYE0601420",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273dbeec63ad914c973e75c24df",
		copyright_text: "© 2015 Apple Corps Ltd",
		download_url: null,
		lyrics: null,
		popularity: 65,
		album_id: "3KzAvEXcqJKBF97HrXwlgf",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 27,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Cleo Sol - Sunshine.mp3`,
		name: "Sunshine",
		artists: ["Cleo Sol"],
		artist: "Cleo Sol",
		genres: ["alternative r&b", "uk contemporary r&b", "uk funky"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Mother",
		album_artist: "Cleo Sol",
		duration: 262960,
		year: "2021",
		date: "2021-08-20",
		track_number: 5,
		tracks_count: 12,
		song_id: "1el1feH98jWUrPpYmu5jN8",
		explicit: false,
		publisher: "Forever Living Originals",
		url: "https://open.spotify.com/track/1el1feH98jWUrPpYmu5jN8",
		isrc: "UKMEH2100104",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2733335e63f35e6cd4d0e8f8aa8",
		copyright_text: "2021 Forever Living Originals",
		download_url: null,
		lyrics: null,
		popularity: 61,
		album_id: "3cDl7l5FGQi93NgtqFR1gR",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 29,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Marvin Gaye - Dream of a Lifetime.mp3`,
		name: "Dream of a Lifetime",
		artists: ["Marvin Gaye"],
		artist: "Marvin Gaye",
		genres: [
			"classic soul",
			"motown",
			"neo soul",
			"northern soul",
			"quiet storm",
			"soul",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Dream Of A Lifetime",
		album_artist: "Marvin Gaye",
		duration: 228933,
		year: "1985",
		date: "1985-05-21",
		track_number: 8,
		tracks_count: 8,
		song_id: "3zTwbOeZytnajTFYKh9MWN",
		explicit: false,
		publisher: "Columbia",
		url: "https://open.spotify.com/track/3zTwbOeZytnajTFYKh9MWN",
		isrc: "USSM10100089",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273c4cbbffce1113811fe4cf6ea",
		copyright_text: "(P) 1985, 1986 CBS Inc.",
		download_url: null,
		lyrics: null,
		popularity: 30,
		album_id: "3R77KUZFEdUDsPcOCTRkPf",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 28,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Sade - Love Is Stronger Than Pride.mp3`,
		name: "Love Is Stronger Than Pride",
		artists: ["Sade"],
		artist: "Sade",
		genres: ["british soul", "sophisti-pop"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Stronger Than Pride",
		album_artist: "Sade",
		duration: 258026,
		year: "1988",
		date: "1988-05-03",
		track_number: 1,
		tracks_count: 10,
		song_id: "5Qrcxc2YPomtX6UB0bwNaf",
		explicit: false,
		publisher: "Epic",
		url: "https://open.spotify.com/track/5Qrcxc2YPomtX6UB0bwNaf",
		isrc: "GBBBM9200011",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2738d6c05fb48d5834d425128bf",
		copyright_text: "(P) 1988 Sony Music Entertainment UK Limited",
		download_url: null,
		lyrics: null,
		popularity: 57,
		album_id: "2y7DbLcG7L5BNx1IkY1PoK",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 30,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Biking With Francis, Garrett Sparrow, Max Leonard, Joshua Raw - TYPE TIME.mp3`,
		name: "TYPE TIME",
		artists: [
			"Biking With Francis",
			"Garrett Sparrow",
			"Max Leonard",
			"Joshua Raw",
		],
		artist: "Biking With Francis",
		genres: [],
		disc_number: 1,
		disc_count: 1,
		album_name: "TYPE TIME",
		album_artist: "Biking With Francis",
		duration: 212000,
		year: "2023",
		date: "2023-04-26",
		track_number: 1,
		tracks_count: 1,
		song_id: "56nmFFVNAVuElZkFTopkoK",
		explicit: true,
		publisher: "Biking with Francis",
		url: "https://open.spotify.com/track/56nmFFVNAVuElZkFTopkoK",
		isrc: "QZHNA2321823",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273a0d8b03ea58893bd3b6d9439",
		copyright_text: "2023 Biking with Francis",
		download_url: null,
		lyrics: null,
		popularity: 40,
		album_id: "2LuayShXpp12sctjzSczjH",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 32,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Japanese Breakfast - Kokomo, IN.mp3`,
		name: "Kokomo, IN",
		artists: ["Japanese Breakfast"],
		artist: "Japanese Breakfast",
		genres: [
			"art pop",
			"eugene indie",
			"indie pop",
			"indie rock",
			"philly indie",
		],
		disc_number: 1,
		disc_count: 1,
		album_name: "Jubilee",
		album_artist: "Japanese Breakfast",
		duration: 218744,
		year: "2021",
		date: "2021-06-04",
		track_number: 3,
		tracks_count: 10,
		song_id: "0O4sIQ728ugLlwBVaxF8UM",
		explicit: false,
		publisher: "Dead Oceans",
		url: "https://open.spotify.com/track/0O4sIQ728ugLlwBVaxF8UM",
		isrc: "USJ5G2022503",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273b103a69ed742a7735a2ba7e8",
		copyright_text: "2021 Dead Oceans",
		download_url: null,
		lyrics: null,
		popularity: 58,
		album_id: "1uD1kdwTWH1DZQZqGKz6rY",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 31,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Jordan Ward - SIDEKICK (with Joyce Wrice) - BONUS.mp3`,
		name: "SIDEKICK (with Joyce Wrice) - BONUS",
		artists: ["Jordan Ward", "Joyce Wrice"],
		artist: "Jordan Ward",
		genres: ["indie hip hop", "indie r&b"],
		disc_number: 1,
		disc_count: 1,
		album_name: "FORWARD",
		album_artist: "Jordan Ward",
		duration: 134013,
		year: "2023",
		date: "2023-03-03",
		track_number: 13,
		tracks_count: 14,
		song_id: "0h3BFerMyzUaYYh2nwGiX3",
		explicit: true,
		publisher: "ARTium Recordings, LLC/Interscope Records",
		url: "https://open.spotify.com/track/0h3BFerMyzUaYYh2nwGiX3",
		isrc: "USUM72300087",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b27317696caf00b6e0ac16cbbba4",
		copyright_text: "© 2023 Interscope Records",
		download_url: null,
		lyrics: null,
		popularity: 55,
		album_id: "367frJ4GG9UMlXlMrVanYL",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 33,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Noname, Raury, Cam O'bi - Diddy Bop.mp3`,
		name: "Diddy Bop",
		artists: ["Noname", "Raury", "Cam O'bi"],
		artist: "Noname",
		genres: ["alternative r&b", "chicago rap"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Telefone",
		album_artist: "Noname",
		duration: 208000,
		year: "2016",
		date: "2016-07-31",
		track_number: 3,
		tracks_count: 10,
		song_id: "7CRPXJt3IVC7V0VcM0PSQi",
		explicit: true,
		publisher: "Noname",
		url: "https://open.spotify.com/track/7CRPXJt3IVC7V0VcM0PSQi",
		isrc: "TCACR1618925",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273d684ea63f359ff9a83c10bc8",
		copyright_text: "(C) 2016 Noname",
		download_url: null,
		lyrics: null,
		popularity: 58,
		album_id: "5kjqLxeQxdW3CcUdOXuO2c",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 34,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}grentperez - When The Day Is Done.mp3`,
		name: "When The Day Is Done",
		artists: ["grentperez"],
		artist: "grentperez",
		genres: ["bedroom r&b"],
		disc_number: 1,
		disc_count: 1,
		album_name: "When We Were Younger",
		album_artist: "grentperez",
		duration: 180201,
		year: "2023",
		date: "2023-06-02",
		track_number: 7,
		tracks_count: 7,
		song_id: "2L1F7gMujKPASRZ5MDAbr2",
		explicit: false,
		publisher: "Fast Friends",
		url: "https://open.spotify.com/track/2L1F7gMujKPASRZ5MDAbr2",
		isrc: "QM4TX2378113",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b2734061f6965ab6f93fb0740b16",
		copyright_text:
			"(C) 2023 Fast Friends under exclusive license to AWAL Recordings America, Inc.",
		download_url: null,
		lyrics: null,
		popularity: 56,
		album_id: "2G2NSV9SHG1WlgL4u5qZ9w",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 36,
		list_length: 36,
	},
	{
		path: `${jqPlaylistPath}Reuben James, House of EL - Love Stoned.mp3`,
		name: "Love Stoned",
		artists: ["Reuben James", "House of EL"],
		artist: "Reuben James",
		genres: ["uk contemporary r&b"],
		disc_number: 1,
		disc_count: 1,
		album_name: "Love Stoned",
		album_artist: "Reuben James",
		duration: 168266,
		year: "2023",
		date: "2023-05-05",
		track_number: 1,
		tracks_count: 1,
		song_id: "2ushzNQ16t37taQsEVqwDv",
		explicit: false,
		publisher: "Rufio Records",
		url: "https://open.spotify.com/track/2ushzNQ16t37taQsEVqwDv",
		isrc: "QM6MZ2302291",
		cover_url:
			"https://i.scdn.co/image/ab67616d0000b273373c4adbda46c8de2299e02f",
		copyright_text: "(C) 2023 Rufio Records",
		download_url: null,
		lyrics: null,
		popularity: 28,
		album_id: "7cTkYZdldeJjm58kehLaxq",
		list_name: "JaM Queue",
		list_url: "https://open.spotify.com/playlist/3ItRPQB12qcNnpsE7WYdOy",
		list_position: 35,
		list_length: 36,
	},
];
